<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Configurations>Debug;Release;DebugCore;ReleaseCore</Configurations>
    <Platforms>AnyCPU</Platforms>
    <TargetFramework>net10.0</TargetFramework>
    <TargetFramework Condition="'$(Configuration)' == 'DebugCore'">net10.0</TargetFramework>
    <TargetFramework Condition="'$(Configuration)' == 'ReleaseCore'">net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputType>Exe</OutputType>
    <OutputPath>bin\$(Configuration)\</OutputPath>

  </PropertyGroup>

</Project>
