<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Condition=" '$(MSBuildThisFileDirectory)' != '' ">
    <SharpSvnPlatform Condition=" '$(SharpSvnPlatform)' == '' And '$(PlatformTarget)' != '' ">$(PlatformTarget)</SharpSvnPlatform>
    <SharpSvnPlatform Condition=" '$(SharpSvnPlatform)' == '' And '$(Platform)' != '' And '$(Platform)' != 'AnyCPU' And '$(Platform)' != 'Any CPU' ">$(Platform)</SharpSvnPlatform>
    <SharpSvnPlatform Condition=" '$(SharpSvnPlatform)' == '' ">x64</SharpSvnPlatform>
    <SharpSvnRuntimeTargetFramework Condition=" '$(SharpSvnRuntimeTargetFramework)' == '' And '$(TargetFramework)' != '' ">$(TargetFramework)</SharpSvnRuntimeTargetFramework>
    <SharpSvnRuntimeTargetFramework Condition=" '$(SharpSvnRuntimeTargetFramework)' == '' Or !Exists('$(MSBuildThisFileDirectory)\..\runtimes\win-x64\lib\$(SharpSvnRuntimeTargetFramework)') ">net10.0-windows</SharpSvnRuntimeTargetFramework>
    <!-- Default -->
    <SharpSvnRuntimeDir>$(MSBuildThisFileDirectory)\..\runtimes\win-x64\lib\$(SharpSvnRuntimeTargetFramework)\</SharpSvnRuntimeDir>
    <!-- Overrides -->
    <SharpSvnRuntimeDir Condition=" '$(SharpSvnPlatform)' == 'x86'   ">$(MSBuildThisFileDirectory)\..\runtimes\win-x86\lib\$(SharpSvnRuntimeTargetFramework)\</SharpSvnRuntimeDir>
    <SharpSvnRuntimeDir Condition=" '$(SharpSvnPlatform)' == 'Win32' ">$(MSBuildThisFileDirectory)\..\runtimes\win-x86\lib\$(SharpSvnRuntimeTargetFramework)\</SharpSvnRuntimeDir>
    <SharpSvnRuntimeDir Condition=" '$(SharpSvnPlatform)' == 'x64'   ">$(MSBuildThisFileDirectory)\..\runtimes\win-x64\lib\$(SharpSvnRuntimeTargetFramework)\</SharpSvnRuntimeDir>
    <SharpSvnRuntimeDir Condition=" '$(SharpSvnPlatform)' == 'AMD64' ">$(MSBuildThisFileDirectory)\..\runtimes\win-x64\lib\$(SharpSvnRuntimeTargetFramework)\</SharpSvnRuntimeDir>
    <SharpSvnRuntimeDir Condition=" '$(SharpSvnPlatform)' == 'ARM64' ">$(MSBuildThisFileDirectory)\..\runtimes\win-arm64\lib\$(SharpSvnRuntimeTargetFramework)\</SharpSvnRuntimeDir>
  </PropertyGroup>

  <ItemGroup Condition=" '$(SharpSvnRuntimeDir)' != '' ">
    <SharpSvnExternalFiles Include="$(SharpSvnRuntimeDir)\*.dll" Condition=" '$(CopySharpSvnExternals)' != 'false' " />
    <SharpSvnExternalFiles Include="$(SharpSvnRuntimeDir)\*.svnExe" Condition=" '$(CopySharpSvnExternals)' != 'false' " />
    <SharpSvnExternalFiles Include="$(SharpSvnRuntimeDir)\*.svnDll" Condition=" '$(CopySharpSvnExternals)' != 'false' " />
    <SharpSvnExternalFiles Include="$(SharpSvnRuntimeDir)\*.pdb" Condition=" '$(CopySharpSvnSymbols)' == 'true' " />
    <SharpSvnExternalFiles Include="$(SharpSvnRuntimeDir)\*.xml" Condition=" '$(CopySharpSvnExternals)' != 'false' And '$(CopySharpSvnDocumentation)' != 'false'" />
  </ItemGroup>

  <ItemGroup Condition="'$(ContentSharpSvnExternalFiles)' != '' And
                        '$(ContentSharpSvnExternalFiles)' != 'false' And
                        '@(SharpSvnExternalFiles)' != ''">
    <Content Include="@(SharpSvnExternalFiles)">
      <Link>%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>false</Visible>
    </Content>
  </ItemGroup>

  <Target Name="SharpSvnCopyExternalFiles" BeforeTargets="Build">
    <Copy
      SourceFiles="@(SharpSvnExternalFiles)"
      DestinationFiles="@(SharpSvnExternalFiles -> '$(OutDir)%(Filename)%(Extension)')"
      SkipUnchangedFiles="true" />
  </Target>

  <Target Name="SharpSvnCleanDbFiles" BeforeTargets="Clean">
    <Delete Files="@(SharpSvnExternalFiles -> '$(OutDir)%(Filename)%(Extension)')" />
  </Target>
</Project>
